# Generated by Django 5.1.2 on 2024-10-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='barcodeImage',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/employees/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='barcode',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
