# Generated by Django 5.1.2 on 2024-11-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_item_barcodeimage_alter_item_barcode'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='barcodeImage',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/employees/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='heldItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.item'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='barcode',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
