# Generated by Django 5.1.2 on 2024-11-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_item_barcodeean8_alter_item_barcode'),
        ('employees', '0002_employee_barcodeimage_alter_employee_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='heldItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.item'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='barcode',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
