# Generated by Django 5.1.2 on 2024-10-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('idNum', models.IntegerField()),
                ('available', models.BooleanField()),
                ('dateTaken', models.DateTimeField()),
            ],
        ),
    ]
