# Generated by Django 5.1.2 on 2024-10-29 02:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('serialNumber', models.IntegerField(default=None, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(default='Available', max_length=255)),
                ('notes', models.TextField(default=None, max_length=500, null=True)),
                ('dateTaken', models.DateField(default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('barcode', models.CharField(default=None, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be exactly 8 digits.', regex='^2\\d{7}$')])),
                ('holder', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
