# Generated by Django 5.1.1 on 2024-10-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
