# Generated by Django 5.1.2 on 2024-11-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_item_barcodeimage_alter_item_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcodeEAN8',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, unique=True),
        ),
    ]
