# Generated by Django 5.1.2 on 2024-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_item_barcodeimage_alter_item_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='serialNumber',
        ),
        migrations.AddField(
            model_name='item',
            name='expirationDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='timeTaken',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
