# Generated by Django 5.1.1 on 2024-10-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_item_location_item_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='idNum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
