# Generated by Django 5.1.2 on 2024-11-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_item_barcodeean8_alter_item_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='serialNumber',
        ),
    ]
