# Generated by Django 5.1.1 on 2024-10-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_item_available_alter_item_datetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateTaken',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
