# Generated by Django 5.1.2 on 2024-11-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_item_expirationdate_item_timetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateTaken',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
