# Generated by Django 5.1.2 on 2024-10-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_item_notes'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='idNum',
        ),
        migrations.AddField(
            model_name='item',
            name='holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='itemId',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='Available', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateTaken',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
