# Generated by Django 5.1.2 on 2024-11-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_item_datetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timeTaken',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
