# Generated by Django 5.1.2 on 2024-10-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_item_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
