# Generated by Django 5.1.2 on 2024-11-25 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_item_timetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timeTaken',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
