# Generated by Django 5.1.2 on 2024-11-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_item_timetaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='timeTaken',
        ),
    ]
